-- ============================================================================
-- Klarify — 008_sprint3_documents.sql
--
-- Sprint 3 — Document Analyser (S3-A1, S3-B1).
--
-- Extends `uploaded_documents` from the Sprint-0 minimal columns into the
-- full surface CLAUDE.md S3-A1 specifies. Purely additive on data; one
-- breaking but transparent normalisation: `urgency_level` is moved from
-- lowercase to uppercase enum so it matches CLAUDE.md §6 analyser output
-- (CRITICAL / HIGH / MEDIUM / LOW). Existing rows are upper-cased in place.
--
-- New columns:
--
--   original_filename   TEXT
--     The user-supplied filename. Distinct from `filename` which we still
--     use for display + email subject lines. `s3_key` is the secure path
--     and never contains the original filename (CLAUDE.md §16 Rule 3).
--
--   file_size           INTEGER
--     Bytes. Enforced ≤ 10 MB at the API layer (S3-A1 spec).
--
--   extracted_text      TEXT
--     OCR output (or the original text for paste-text uploads). Stored so
--     we can re-analyse without re-running expensive Textract calls.
--
--   ocr_method          TEXT
--     'pdf-parse' | 'textract' | 'paste' — for ops + cost attribution.
--
--   ocr_completed_at    TIMESTAMPTZ
--     Stage timestamp for the dashboard processing-stepper UI.
--
--   draft_response      TEXT
--     The full draft acknowledgement letter generated by the analyser.
--     Stored separately from analysis_result so the .docx exporter can
--     stream it without parsing JSON.
--
--   status              TEXT  ('pending'|'extracting'|'analysing'|'complete'|'error')
--     The state machine the analysis queue advances. The Sprint-3 UI
--     polls GET /api/documents/:id/status which reads this column.
--
--   error_message       TEXT
--     Populated when status='error' so the UI can surface a friendly
--     reason (mirrors the Anthropic error classifier on the chat path).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Normalise urgency_level to uppercase
-- ---------------------------------------------------------------------------
-- The Sprint-0 CHECK was lowercase. CLAUDE.md §6 (DOCUMENT_ANALYSER_PROMPT)
-- mandates uppercase. The downstream email service (apps/api/src/services/
-- documentAnalysisNotify.ts) and the Sprint 3 dashboard banner all key off
-- uppercase. Single source of truth: uppercase. Update existing rows in
-- place, then swap the constraint.
ALTER TABLE public.uploaded_documents
  DROP CONSTRAINT IF EXISTS uploaded_documents_urgency_level_check;

UPDATE public.uploaded_documents
  SET urgency_level = UPPER(urgency_level)
  WHERE urgency_level IS NOT NULL;

ALTER TABLE public.uploaded_documents
  ADD CONSTRAINT uploaded_documents_urgency_level_check
  CHECK (urgency_level IS NULL
         OR urgency_level IN ('CRITICAL','HIGH','MEDIUM','LOW'));

-- The 001-era partial index referenced lowercase values — rebuild against
-- uppercase so the "critical documents on dashboard" query stays fast.
DROP INDEX IF EXISTS public.idx_uploaded_docs_urgency;
CREATE INDEX IF NOT EXISTS idx_uploaded_docs_urgency
  ON public.uploaded_documents(org_id, urgency_level)
  WHERE urgency_level IN ('CRITICAL','HIGH');

-- ---------------------------------------------------------------------------
-- 2. New Sprint 3 columns
-- ---------------------------------------------------------------------------
ALTER TABLE public.uploaded_documents
  ADD COLUMN IF NOT EXISTS original_filename TEXT,
  ADD COLUMN IF NOT EXISTS file_size         INTEGER,
  ADD COLUMN IF NOT EXISTS extracted_text    TEXT,
  ADD COLUMN IF NOT EXISTS ocr_method        TEXT
    CHECK (ocr_method IS NULL OR ocr_method IN ('pdf-parse','textract','paste')),
  ADD COLUMN IF NOT EXISTS ocr_completed_at  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS draft_response    TEXT,
  ADD COLUMN IF NOT EXISTS status            TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','extracting','analysing','complete','error')),
  ADD COLUMN IF NOT EXISTS error_message     TEXT;

-- Backfill: any existing rows (Sprint 0 / 1 test data) that have an
-- analysis_result should be considered complete. Everything else stays
-- 'pending' so the queue can reprocess on demand.
UPDATE public.uploaded_documents
  SET status = 'complete'
  WHERE analysis_result IS NOT NULL
    AND status = 'pending';

-- ---------------------------------------------------------------------------
-- 3. Indices supporting Sprint 3 access patterns
-- ---------------------------------------------------------------------------
-- Dashboard "Recent documents" widget — last 3 per org by uploaded_at.
CREATE INDEX IF NOT EXISTS idx_uploaded_docs_org_uploaded
  ON public.uploaded_documents(org_id, uploaded_at DESC);

-- Status filter — analysis queue polls for unfinished jobs on cold start.
CREATE INDEX IF NOT EXISTS idx_uploaded_docs_status_pending
  ON public.uploaded_documents(status, uploaded_at)
  WHERE status IN ('pending','extracting','analysing');

-- ---------------------------------------------------------------------------
-- 4. RLS — defensive re-grant
-- ---------------------------------------------------------------------------
-- 002_rls.sql already enabled RLS on uploaded_documents with policies
-- scoped to is_org_member(org_id). The new columns inherit those policies
-- automatically (RLS is per-row not per-column). Nothing to add here, but
-- we re-assert for documentation:
--   * SELECT/INSERT/UPDATE allowed where is_org_member(org_id) = true.
--   * Service-role bypass for the analysis queue.
