// =============================================================================
// .docx draft-response export (CLAUDE.md S3-B3).
//
// Takes the draft response generated by the analyser and renders it as a
// properly formatted Word document with company letterhead, recipient
// block, draft body, and the mandatory AI-assistance footer. Uploads to
// S3 under a per-org/per-user `drafts/` prefix and returns a 1-hour
// signed download URL.
//
// We render the .docx server-side rather than client-side so:
//   * The signature/letterhead always reflects the latest org profile.
//   * The disclaimer footer is impossible for the user to strip.
//   * Mobile clients can use the same export endpoint without bundling
//     the `docx` library on-device.
// =============================================================================
import { randomUUID } from 'node:crypto';
import { Buffer } from 'node:buffer';
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from 'docx';
import { prisma } from '../db.js';
import { getSignedDownloadUrl, putObject } from './s3.js';

export interface ExportDraftResult {
  downloadUrl: string;
  expiresAt: string;
  s3Key: string;
}

export class ExportDraftError extends Error {
  constructor(
    message: string,
    public readonly code: 'NOT_FOUND' | 'NO_DRAFT' | 'RENDER_FAILED',
    public readonly httpStatus: number,
  ) {
    super(message);
    this.name = 'ExportDraftError';
  }
}

/** Build the Word document for a completed document analysis + persist it. */
export async function exportDraftAsDocx(
  documentId: string,
  userId: string,
): Promise<ExportDraftResult> {
  const doc = await prisma.uploadedDocument.findFirst({
    where: { id: documentId, userId },
    include: {
      org: { include: { members: { include: { user: true } } } },
    },
  });
  if (!doc) {
    throw new ExportDraftError(
      'Document not found.',
      'NOT_FOUND',
      404,
    );
  }
  if (!doc.draftResponse || doc.draftResponse.trim().length === 0) {
    throw new ExportDraftError(
      'No draft response available yet. Wait for analysis to complete.',
      'NO_DRAFT',
      409,
    );
  }

  const owner =
    doc.org.members.find((m) => m.role === 'owner') ?? doc.org.members[0];
  const orgContext = {
    companyName: doc.org.name,
    signatoryName: owner?.user.name ?? 'Compliance Officer',
    signatoryEmail: owner?.user.email ?? null,
  };

  const analysis = doc.analysisResult as
    | { issuing_regulator?: { name?: string; department?: string } }
    | null;
  const recipient = {
    name: analysis?.issuing_regulator?.name ?? 'The Director General',
    department: analysis?.issuing_regulator?.department ?? null,
  };

  // Use the document filename as a best-effort reference number — most
  // regulator letters carry a reference in the filename when uploaded
  // (e.g. "SEC_NIG-2026-0214_letter.pdf").
  const reference = inferReference(doc.filename);

  const buffer = await renderDocx({
    org: orgContext,
    recipient,
    reference,
    draftBody: doc.draftResponse,
  });

  const s3Key = `${doc.orgId}/${userId}/drafts/${randomUUID()}_draft.docx`;
  await putObject({
    key: s3Key,
    body: buffer,
    contentType:
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    downloadFilename: 'Klarify_draft_response.docx',
  });

  const ttlSeconds = 3600;
  const downloadUrl = await getSignedDownloadUrl(s3Key, ttlSeconds);
  const expiresAt = new Date(Date.now() + ttlSeconds * 1000).toISOString();

  return { downloadUrl, expiresAt, s3Key };
}

interface RenderArgs {
  org: { companyName: string; signatoryName: string; signatoryEmail: string | null };
  recipient: { name: string; department: string | null };
  reference: string;
  draftBody: string;
}

/** Compose the docx Buffer using `docx`. Pure — exposed for unit testing. */
export async function renderDocx(args: RenderArgs): Promise<Buffer> {
  const today = new Date().toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // The draft itself comes back with paragraph breaks; split on blank
  // lines so each paragraph renders as its own <w:p> rather than a
  // single multi-line paragraph (preserves leading bullets / indentation
  // that the analyser sometimes adds).
  const draftParas = args.draftBody
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);

  const document = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Company letterhead
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [bold(args.org.companyName)],
          }),
          ...(args.org.signatoryEmail
            ? [
                new Paragraph({
                  children: [text(args.org.signatoryEmail)],
                  spacing: { after: 200 },
                }),
              ]
            : []),

          // Date
          new Paragraph({
            children: [text(today)],
            spacing: { after: 200 },
          }),

          // Recipient block
          new Paragraph({
            children: [text(args.recipient.name)],
          }),
          ...(args.recipient.department
            ? [new Paragraph({ children: [text(args.recipient.department)] })]
            : []),
          new Paragraph({ children: [text('')], spacing: { after: 200 } }),

          // Subject line
          new Paragraph({
            children: [bold(`RE: ${args.reference}`)],
            spacing: { after: 200 },
          }),

          // Salutation
          new Paragraph({ children: [text('Dear Sir/Ma,')] }),
          new Paragraph({ children: [text('')] }),

          // Body paragraphs
          ...draftParas.map(
            (p) =>
              new Paragraph({
                children: [text(p)],
                spacing: { after: 160 },
              }),
          ),

          // Sign-off
          new Paragraph({ children: [text('')] }),
          new Paragraph({ children: [text('Yours sincerely,')] }),
          new Paragraph({ children: [text('')] }),
          new Paragraph({ children: [text('')] }),
          new Paragraph({ children: [bold(args.org.signatoryName)] }),
          new Paragraph({
            children: [text(`On behalf of ${args.org.companyName}`)],
            spacing: { after: 400 },
          }),

          // AI-assistance footer — italic + muted, never removable.
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text:
                  'This response was drafted with the assistance of Klarify regulatory advisory platform. ' +
                  'It has been reviewed and approved for submission.',
                italics: true,
                size: 18, // 9pt
                color: '777777',
              }),
            ],
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(document);
}

function bold(t: string): TextRun {
  return new TextRun({ text: t, bold: true });
}
function text(t: string): TextRun {
  return new TextRun({ text: t });
}

/**
 * Pull a plausible reference number out of an uploaded filename, e.g.:
 *   "SEC_NIG-2026-0214_letter.pdf" → "SEC_NIG-2026-0214"
 *   "CBN-PSM-2025-0143.pdf"        → "CBN-PSM-2025-0143"
 *   "scan.pdf"                     → "Your notice"
 */
function inferReference(filename: string): string {
  const noExt = filename.replace(/\.[A-Za-z0-9]{1,5}$/, '');
  // Look for a chunk that has at least 2 uppercase letters + a digit
  // and is bounded by underscores/dashes/start/end.
  const m = noExt.match(/[A-Z]{2,}[A-Z0-9_-]*\d[A-Z0-9_-]*/);
  if (m && m[0].length >= 4) return m[0];
  // Year-only references like "2026-05" still useful as a stub.
  const yr = noExt.match(/\b(20\d{2})[-/.]?\d{0,4}\b/);
  if (yr) return `Your notice dated ${yr[0]}`;
  return 'Your notice';
}
